---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: auto-repair-shop
  labels:
    app: auto-repair-shop
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auto-repair-shop-secret
  namespace: auto-repair-shop
  labels:
    app: auto-repair-shop
    tier: backend
    environment: production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: auto-repair-shop-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: ${AWS_SECRET_NAME}
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: ${AWS_SECRET_NAME}
        property: DB_PASSWORD
    - secretKey: DB_HOST
      remoteRef:
        key: ${AWS_SECRET_NAME}
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: ${AWS_SECRET_NAME}
        property: DB_PORT
    - secretKey: DB_NAME
      remoteRef:
        key: ${AWS_SECRET_NAME}
        property: DB_NAME
    - secretKey: DATABASE_URL
      remoteRef:
        key: ${AWS_SECRET_NAME}
        property: DATABASE_URL
    - secretKey: JWT_ACCESS_TOKEN_SECRET
      remoteRef:
        key: ${AWS_SECRET_NAME}
        property: JWT_ACCESS_TOKEN_SECRET
    - secretKey: JWT_REFRESH_TOKEN_SECRET
      remoteRef:
        key: ${AWS_SECRET_NAME}
        property: JWT_REFRESH_TOKEN_SECRET
    - secretKey: SMTP_USERNAME
      remoteRef:
        key: ${AWS_SECRET_NAME}
        property: SMTP_USERNAME
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: ${AWS_SECRET_NAME}
        property: SMTP_PASSWORD
